### ISSUE TITLE
Getting an error when trying to reproject and stitch GOES 13,16,17,Himawari8, and GK2A

### ISSUE THREAD

**Issue by creinemann** [nullpainter/sanchez#54]
# Describe the bug
when trying to reproject and stitch GOES 13,16,17,Himawari8, and GK2A combined

## Expected behavior
Almost complete global coverag
## Real behavior
Only is permitting 13,16,17 to project, even though Himawari  and GK2A are shown as being processed

##This is the error:
y
[16:14:28 INF] Using cached underlay
[16:14:28 INF] Blending with underlay
[16:14:28 ERR] Workflow b9ae6072-0e18-4540-b808-07bfc62a1c78 raised error on step 22 Message: Crop rectangle should be smaller than the source bounds. (Parameter 'cropRectangle')
System.ArgumentException: Crop rectangle should be smaller than the source bounds. (Parameter 'cropRectangle')
   at SixLabors.ThrowHelper.ThrowArgumentException(String message, String name)
   at SixLabors.ImageSharp.Processing.Processors.Transforms.CropProcessor..ctor(Rectangle cropRectangle, Size sourceSize)
   at SixLabors.ImageSharp.Processing.CropExtensions.Crop(IImageProcessingContext source, Rectangle cropRectangle)
   at Sanchez.Workflow.Steps.Equirectangular.Stitch.CropImage.<Run>b__14_0(IImageProcessingContext ctx)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Configuration configuration, Action`1 operation)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Action`1 operation)
   at Sanchez.Workflow.Steps.Equirectangular.Stitch.CropImage.Run(IStepExecutionContext context)
   at WorkflowCore.Models.StepBody.RunAsync(IStepExecutionContext context)
   at WorkflowCore.Services.WorkflowExecutor.ExecuteStep(WorkflowInstance workflow, WorkflowStep step, ExecutionPointer pointer, WorkflowExecutorResult wfResult, WorkflowDefinition def, CancellationToken cancellationToken)
   at WorkflowCore.Services.WorkflowExecutor.Execute(WorkflowInstance workflow, CancellationToken cancellationToken)
[16:14:28 ERR] Unhandled failure in workflow
System.ArgumentException: Crop rectangle should be smaller than the source bounds. (Parameter 'cropRectangle')
   at SixLabors.ThrowHelper.ThrowArgumentException(String message, String name)
   at SixLabors.ImageSharp.Processing.Processors.Transforms.CropProcessor..ctor(Rectangle cropRectangle, Size sourceSize)
   at SixLabors.ImageSharp.Processing.CropExtensions.Crop(IImageProcessingContext source, Rectangle cropRectangle)
   at Sanchez.Workflow.Steps.Equirectangular.Stitch.CropImage.<Run>b__14_0(IImageProcessingContext ctx)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Configuration configuration, Action`1 operation)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Action`1 operation)
   at Sanchez.Workflow.Steps.Equirectangular.Stitch.CropImage.Run(IStepExecutionContext context)
   at WorkflowCore.Models.StepBody.RunAsync(IStepExecutionContext context)
   at WorkflowCore.Services.WorkflowExecutor.ExecuteStep(WorkflowInstance workflow, WorkflowStep step, ExecutionPointer pointer, WorkflowExecutorResult wfResult, WorkflowDefinition def, CancellationToken cancellationToken)
   at WorkflowCore.Services.WorkflowExecutor.Execute(WorkflowInstance workflow, CancellationToken cancellationToken)

## Environment:
*Please complete the following information to tell us how you are running Sanchez*
```
 - OS: windows
 - Sanchez Version 1.010
```

**Comment by nullpainter** [comment]
Thanks for reporting this. I now have full earth projection working well, but in doing so I've found a few other things I need to fix / add (Electro and GOES 13 have inverted IR images to the rest, plus some performance issues introduced with the change, and a lat / long crop option). 

If you're eager to play, I can throw a build your way but it may be a week or two for a formal release.

**Comment by creinemann** [comment]
I can wait, I have a few irons in the fire now anyway. Thanks!
