### ISSUE TITLE
error while using sanchez

### ISSUE THREAD

**Issue by YD1RUH** [nullpainter/sanchez#77]
[04:46:45 ERR] Workflow 4f74c6fe-3b13-4c63-bf6c-a04abf6f8c12 raised error on step 3 Message: No source files found
FluentValidation.ValidationException: No source files found
   at Sanchez.Workflow.Steps.Common.GetSourceFiles.Run(IStepExecutionContext context)
   at WorkflowCore.Models.StepBody.RunAsync(IStepExecutionContext context)
   at WorkflowCore.Services.WorkflowExecutor.ExecuteStep(WorkflowInstance workflow, WorkflowStep step, ExecutionPointer pointer, WorkflowExecutorResult wfResult, WorkflowDefinition def, CancellationToken cancellationToken)
   at WorkflowCore.Services.WorkflowExecutor.Execute(WorkflowInstance workflow, CancellationToken cancellationToken)
No source files found
[04:46:46 WRN] No source files found

**Comment by nullpainter** [comment]
All details are in the warning above - you've pointed `-s / --source` to a directory or glob that doesn't contain any images that Sanchez can process.

What did you specify for this argument? And what are the filenames of the files that you are expecting Sanchez to process?

**Comment by YD1RUH** [comment]
okay, thank you. it's done..
